<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Countrie;

class CountrySeeder extends Seeder {

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        Countrie::create(['iso' => 'CO', 'pais' => 'Colombia',]);
        Countrie::create(['iso' => 'AF', 'pais' => 'Afganistán',]);
        Countrie::create(['iso' => 'AX', 'pais' => 'Islas Gland',]);
        Countrie::create(['iso' => 'AL', 'pais' => 'Albania',]);
        Countrie::create(['iso' => 'DE', 'pais' => 'Alemania',]);
        Countrie::create(['iso' => 'AD', 'pais' => 'Andorra',]);
        Countrie::create(['iso' => 'AO', 'pais' => 'Angola',]);
        Countrie::create(['iso' => 'AI', 'pais' => 'Anguilla',]);
        Countrie::create(['iso' => 'AQ', 'pais' => 'Antártida',]);
        Countrie::create(['iso' => 'AG', 'pais' => 'Antigua y Barbuda',]);
        Countrie::create(['iso' => 'AN', 'pais' => 'Antillas Holandesas',]);
        Countrie::create(['iso' => 'SA', 'pais' => 'Arabia Saudí',]);
        Countrie::create(['iso' => 'DZ', 'pais' => 'Argelia',]);
        Countrie::create(['iso' => 'AR', 'pais' => 'Argentina',]);
        Countrie::create(['iso' => 'AM', 'pais' => 'Armenia',]);
        Countrie::create(['iso' => 'AW', 'pais' => 'Aruba',]);
        Countrie::create(['iso' => 'AU', 'pais' => 'Australia',]);
        Countrie::create(['iso' => 'AT', 'pais' => 'Austria',]);
        Countrie::create(['iso' => 'AZ', 'pais' => 'Azerbaiyán',]);
        Countrie::create(['iso' => 'BS', 'pais' => 'Bahamas',]);
        Countrie::create(['iso' => 'BH', 'pais' => 'Bahréin',]);
        Countrie::create(['iso' => 'BD', 'pais' => 'Bangladesh',]);
        Countrie::create(['iso' => 'BB', 'pais' => 'Barbados',]);
        Countrie::create(['iso' => 'BY', 'pais' => 'Bielorrusia',]);
        Countrie::create(['iso' => 'BE', 'pais' => 'Bélgica',]);
        Countrie::create(['iso' => 'BZ', 'pais' => 'Belice',]);
        Countrie::create(['iso' => 'BJ', 'pais' => 'Benin',]);
        Countrie::create(['iso' => 'BM', 'pais' => 'Bermudas',]);
        Countrie::create(['iso' => 'BT', 'pais' => 'Bhután',]);
        Countrie::create(['iso' => 'BO', 'pais' => 'Bolivia',]);
        Countrie::create(['iso' => 'BA', 'pais' => 'Bosnia y Herzegovina',]);
        Countrie::create(['iso' => 'BW', 'pais' => 'Botsuana',]);
        Countrie::create(['iso' => 'BV', 'pais' => 'Isla Bouvet',]);
        Countrie::create(['iso' => 'BR', 'pais' => 'Brasil',]);
        Countrie::create(['iso' => 'BN', 'pais' => 'Brunéi',]);
        Countrie::create(['iso' => 'BG', 'pais' => 'Bulgaria',]);
        Countrie::create(['iso' => 'BF', 'pais' => 'Burkina Faso',]);
        Countrie::create(['iso' => 'BI', 'pais' => 'Burundi',]);
        Countrie::create(['iso' => 'CV', 'pais' => 'Cabo Verde',]);
        Countrie::create(['iso' => 'KY', 'pais' => 'Islas Caimán',]);
        Countrie::create(['iso' => 'KH', 'pais' => 'Camboya',]);
        Countrie::create(['iso' => 'CM', 'pais' => 'Camerún',]);
        Countrie::create(['iso' => 'CA', 'pais' => 'Canadá',]);
        Countrie::create(['iso' => 'CF', 'pais' => 'República Centroafricana',]);
        Countrie::create(['iso' => 'TD', 'pais' => 'Chad',]);
        Countrie::create(['iso' => 'CZ', 'pais' => 'República Checa',]);
        Countrie::create(['iso' => 'CL', 'pais' => 'Chile',]);
        Countrie::create(['iso' => 'CN', 'pais' => 'China',]);
        Countrie::create(['iso' => 'CY', 'pais' => 'Chipre',]);
        Countrie::create(['iso' => 'CX', 'pais' => 'Isla de Navidad',]);
        Countrie::create(['iso' => 'VA', 'pais' => 'Ciudad del Vaticano',]);
        Countrie::create(['iso' => 'CC', 'pais' => 'Islas Cocos',]);
        Countrie::create(['iso' => 'KM', 'pais' => 'Comoras',]);
        Countrie::create(['iso' => 'CD', 'pais' => 'República Democrática del Congo',]);
        Countrie::create(['iso' => 'CG', 'pais' => 'Congo',]);
        Countrie::create(['iso' => 'CK', 'pais' => 'Islas Cook',]);
        Countrie::create(['iso' => 'KP', 'pais' => 'Corea del Norte',]);
        Countrie::create(['iso' => 'KR', 'pais' => 'Corea del Sur',]);
        Countrie::create(['iso' => 'CI', 'pais' => 'Costa de Marfil',]);
        Countrie::create(['iso' => 'CR', 'pais' => 'Costa Rica',]);
        Countrie::create(['iso' => 'HR', 'pais' => 'Croacia',]);
        Countrie::create(['iso' => 'CU', 'pais' => 'Cuba',]);
        Countrie::create(['iso' => 'DK', 'pais' => 'Dinamarca',]);
        Countrie::create(['iso' => 'DM', 'pais' => 'Dominica',]);
        Countrie::create(['iso' => 'DO', 'pais' => 'República Dominicana',]);
        Countrie::create(['iso' => 'EC', 'pais' => 'Ecuador',]);
        Countrie::create(['iso' => 'EG', 'pais' => 'Egipto',]);
        Countrie::create(['iso' => 'SV', 'pais' => 'El Salvador',]);
        Countrie::create(['iso' => 'AE', 'pais' => 'Emiratos Árabes Unidos',]);
        Countrie::create(['iso' => 'ER', 'pais' => 'Eritrea',]);
        Countrie::create(['iso' => 'SK', 'pais' => 'Eslovaquia',]);
        Countrie::create(['iso' => 'SI', 'pais' => 'Eslovenia',]);
        Countrie::create(['iso' => 'ES', 'pais' => 'España',]);
        Countrie::create(['iso' => 'UM', 'pais' => 'Islas ultramarinas de Estados Unidos',]);
        Countrie::create(['iso' => 'US', 'pais' => 'Estados Unidos',]);
        Countrie::create(['iso' => 'EE', 'pais' => 'Estonia',]);
        Countrie::create(['iso' => 'ET', 'pais' => 'Etiopía',]);
        Countrie::create(['iso' => 'FO', 'pais' => 'Islas Feroe',]);
        Countrie::create(['iso' => 'PH', 'pais' => 'Filipinas',]);
        Countrie::create(['iso' => 'FI', 'pais' => 'Finlandia',]);
        Countrie::create(['iso' => 'FJ', 'pais' => 'Fiyi',]);
        Countrie::create(['iso' => 'FR', 'pais' => 'Francia',]);
        Countrie::create(['iso' => 'GA', 'pais' => 'Gabón',]);
        Countrie::create(['iso' => 'GM', 'pais' => 'Gambia',]);
        Countrie::create(['iso' => 'GE', 'pais' => 'Georgia',]);
        Countrie::create(['iso' => 'GS', 'pais' => 'Islas Georgias del Sur y Sandwich del Sur',]);
        Countrie::create(['iso' => 'GH', 'pais' => 'Ghana',]);
        Countrie::create(['iso' => 'GI', 'pais' => 'Gibraltar',]);
        Countrie::create(['iso' => 'GD', 'pais' => 'Granada',]);
        Countrie::create(['iso' => 'GR', 'pais' => 'Grecia',]);
        Countrie::create(['iso' => 'GL', 'pais' => 'Groenlandia',]);
        Countrie::create(['iso' => 'GP', 'pais' => 'Guadalupe',]);
        Countrie::create(['iso' => 'GU', 'pais' => 'Guam',]);
        Countrie::create(['iso' => 'GT', 'pais' => 'Guatemala',]);
        Countrie::create(['iso' => 'GF', 'pais' => 'Guayana Francesa',]);
        Countrie::create(['iso' => 'GN', 'pais' => 'Guinea',]);
        Countrie::create(['iso' => 'GQ', 'pais' => 'Guinea Ecuatorial',]);
        Countrie::create(['iso' => 'GW', 'pais' => 'Guinea-Bissau',]);
        Countrie::create(['iso' => 'GY', 'pais' => 'Guyana',]);
        Countrie::create(['iso' => 'HT', 'pais' => 'Haití',]);
        Countrie::create(['iso' => 'HM', 'pais' => 'Islas Heard y McDonald',]);
        Countrie::create(['iso' => 'HN', 'pais' => 'Honduras',]);
        Countrie::create(['iso' => 'HK', 'pais' => 'Hong Kong',]);
        Countrie::create(['iso' => 'HU', 'pais' => 'Hungría',]);
        Countrie::create(['iso' => 'IN', 'pais' => 'India',]);
        Countrie::create(['iso' => 'ID', 'pais' => 'Indonesia',]);
        Countrie::create(['iso' => 'IR', 'pais' => 'Irán',]);
        Countrie::create(['iso' => 'IQ', 'pais' => 'Iraq',]);
        Countrie::create(['iso' => 'IE', 'pais' => 'Irlanda',]);
        Countrie::create(['iso' => 'IS', 'pais' => 'Islandia',]);
        Countrie::create(['iso' => 'IL', 'pais' => 'Israel',]);
        Countrie::create(['iso' => 'IT', 'pais' => 'Italia',]);
        Countrie::create(['iso' => 'JM', 'pais' => 'Jamaica',]);
        Countrie::create(['iso' => 'JP', 'pais' => 'Japón',]);
        Countrie::create(['iso' => 'JO', 'pais' => 'Jordania',]);
        Countrie::create(['iso' => 'KZ', 'pais' => 'Kazajstán',]);
        Countrie::create(['iso' => 'KE', 'pais' => 'Kenia',]);
        Countrie::create(['iso' => 'KG', 'pais' => 'Kirguistán',]);
        Countrie::create(['iso' => 'KI', 'pais' => 'Kiribati',]);
        Countrie::create(['iso' => 'KW', 'pais' => 'Kuwait',]);
        Countrie::create(['iso' => 'LA', 'pais' => 'Laos',]);
        Countrie::create(['iso' => 'LS', 'pais' => 'Lesotho',]);
        Countrie::create(['iso' => 'LV', 'pais' => 'Letonia',]);
        Countrie::create(['iso' => 'LB', 'pais' => 'Líbano',]);
        Countrie::create(['iso' => 'LR', 'pais' => 'Liberia',]);
        Countrie::create(['iso' => 'LY', 'pais' => 'Libia',]);
        Countrie::create(['iso' => 'LI', 'pais' => 'Liechtenstein',]);
        Countrie::create(['iso' => 'LT', 'pais' => 'Lituania',]);
        Countrie::create(['iso' => 'LU', 'pais' => 'Luxemburgo',]);
        Countrie::create(['iso' => 'MO', 'pais' => 'Macao',]);
        Countrie::create(['iso' => 'MK', 'pais' => 'ARY Macedonia',]);
        Countrie::create(['iso' => 'MG', 'pais' => 'Madagascar',]);
        Countrie::create(['iso' => 'MY', 'pais' => 'Malasia',]);
        Countrie::create(['iso' => 'MW', 'pais' => 'Malawi',]);
        Countrie::create(['iso' => 'MV', 'pais' => 'Maldivas',]);
        Countrie::create(['iso' => 'ML', 'pais' => 'Malí',]);
        Countrie::create(['iso' => 'MT', 'pais' => 'Malta',]);
        Countrie::create(['iso' => 'FK', 'pais' => 'Islas Malvinas',]);
        Countrie::create(['iso' => 'MP', 'pais' => 'Islas Marianas del Norte',]);
        Countrie::create(['iso' => 'MA', 'pais' => 'Marruecos',]);
        Countrie::create(['iso' => 'MH', 'pais' => 'Islas Marshall',]);
        Countrie::create(['iso' => 'MQ', 'pais' => 'Martinica',]);
        Countrie::create(['iso' => 'MU', 'pais' => 'Mauricio',]);
        Countrie::create(['iso' => 'MR', 'pais' => 'Mauritania',]);
        Countrie::create(['iso' => 'YT', 'pais' => 'Mayotte',]);
        Countrie::create(['iso' => 'MX', 'pais' => 'México',]);
        Countrie::create(['iso' => 'FM', 'pais' => 'Micronesia',]);
        Countrie::create(['iso' => 'MD', 'pais' => 'Moldavia',]);
        Countrie::create(['iso' => 'MC', 'pais' => 'Mónaco',]);
        Countrie::create(['iso' => 'MN', 'pais' => 'Mongolia',]);
        Countrie::create(['iso' => 'MS', 'pais' => 'Montserrat',]);
        Countrie::create(['iso' => 'MZ', 'pais' => 'Mozambique',]);
        Countrie::create(['iso' => 'MM', 'pais' => 'Myanmar',]);
        Countrie::create(['iso' => 'NA', 'pais' => 'Namibia',]);
        Countrie::create(['iso' => 'NR', 'pais' => 'Nauru',]);
        Countrie::create(['iso' => 'NP', 'pais' => 'Nepal',]);
        Countrie::create(['iso' => 'NI', 'pais' => 'Nicaragua',]);
        Countrie::create(['iso' => 'NE', 'pais' => 'Níger',]);
        Countrie::create(['iso' => 'NG', 'pais' => 'Nigeria',]);
        Countrie::create(['iso' => 'NU', 'pais' => 'Niue',]);
        Countrie::create(['iso' => 'NF', 'pais' => 'Isla Norfolk',]);
        Countrie::create(['iso' => 'NO', 'pais' => 'Noruega',]);
        Countrie::create(['iso' => 'NC', 'pais' => 'Nueva Caledonia',]);
        Countrie::create(['iso' => 'NZ', 'pais' => 'Nueva Zelanda',]);
        Countrie::create(['iso' => 'OM', 'pais' => 'Omán',]);
        Countrie::create(['iso' => 'NL', 'pais' => 'Países Bajos',]);
        Countrie::create(['iso' => 'PK', 'pais' => 'Pakistán',]);
        Countrie::create(['iso' => 'PW', 'pais' => 'Palau',]);
        Countrie::create(['iso' => 'PS', 'pais' => 'Palestina',]);
        Countrie::create(['iso' => 'PA', 'pais' => 'Panamá',]);
        Countrie::create(['iso' => 'PG', 'pais' => 'Papúa Nueva Guinea',]);
        Countrie::create(['iso' => 'PY', 'pais' => 'Paraguay',]);
        Countrie::create(['iso' => 'PE', 'pais' => 'Perú',]);
        Countrie::create(['iso' => 'PN', 'pais' => 'Islas Pitcairn',]);
        Countrie::create(['iso' => 'PF', 'pais' => 'Polinesia Francesa',]);
        Countrie::create(['iso' => 'PL', 'pais' => 'Polonia',]);
        Countrie::create(['iso' => 'PT', 'pais' => 'Portugal',]);
        Countrie::create(['iso' => 'PR', 'pais' => 'Puerto Rico',]);
        Countrie::create(['iso' => 'QA', 'pais' => 'Qatar',]);
        Countrie::create(['iso' => 'GB', 'pais' => 'Reino Unido',]);
        Countrie::create(['iso' => 'RE', 'pais' => 'Reunión',]);
        Countrie::create(['iso' => 'RW', 'pais' => 'Ruanda',]);
        Countrie::create(['iso' => 'RO', 'pais' => 'Rumania',]);
        Countrie::create(['iso' => 'RU', 'pais' => 'Rusia',]);
        Countrie::create(['iso' => 'EH', 'pais' => 'Sahara Occidental',]);
        Countrie::create(['iso' => 'SB', 'pais' => 'Islas Salomón',]);
        Countrie::create(['iso' => 'WS', 'pais' => 'Samoa',]);
        Countrie::create(['iso' => 'AS', 'pais' => 'Samoa Americana',]);
        Countrie::create(['iso' => 'KN', 'pais' => 'San Cristóbal y Nevis',]);
        Countrie::create(['iso' => 'SM', 'pais' => 'San Marino',]);
        Countrie::create(['iso' => 'PM', 'pais' => 'San Pedro y Miquelón',]);
        Countrie::create(['iso' => 'VC', 'pais' => 'San Vicente y las Granadinas',]);
        Countrie::create(['iso' => 'SH', 'pais' => 'Santa Helena',]);
        Countrie::create(['iso' => 'LC', 'pais' => 'Santa Lucía',]);
        Countrie::create(['iso' => 'ST', 'pais' => 'Santo Tomé y Príncipe',]);
        Countrie::create(['iso' => 'SN', 'pais' => 'Senegal',]);
        Countrie::create(['iso' => 'CS', 'pais' => 'Serbia y Montenegro',]);
        Countrie::create(['iso' => 'SC', 'pais' => 'Seychelles',]);
        Countrie::create(['iso' => 'SL', 'pais' => 'Sierra Leona',]);
        Countrie::create(['iso' => 'SG', 'pais' => 'Singapur',]);
        Countrie::create(['iso' => 'SY', 'pais' => 'Siria',]);
        Countrie::create(['iso' => 'SO', 'pais' => 'Somalia',]);
        Countrie::create(['iso' => 'LK', 'pais' => 'Sri Lanka',]);
        Countrie::create(['iso' => 'SZ', 'pais' => 'Suazilandia',]);
        Countrie::create(['iso' => 'ZA', 'pais' => 'Sudáfrica',]);
        Countrie::create(['iso' => 'SD', 'pais' => 'Sudán',]);
        Countrie::create(['iso' => 'SE', 'pais' => 'Suecia',]);
        Countrie::create(['iso' => 'CH', 'pais' => 'Suiza',]);
        Countrie::create(['iso' => 'SR', 'pais' => 'Surinam',]);
        Countrie::create(['iso' => 'SJ', 'pais' => 'Svalbard y Jan Mayen',]);
        Countrie::create(['iso' => 'TH', 'pais' => 'Tailandia',]);
        Countrie::create(['iso' => 'TW', 'pais' => 'Taiwán',]);
        Countrie::create(['iso' => 'TZ', 'pais' => 'Tanzania',]);
        Countrie::create(['iso' => 'TJ', 'pais' => 'Tayikistán',]);
        Countrie::create(['iso' => 'IO', 'pais' => 'Territorio Británico del Océano Índico',]);
        Countrie::create(['iso' => 'TF', 'pais' => 'Territorios Australes Franceses',]);
        Countrie::create(['iso' => 'TL', 'pais' => 'Timor Oriental',]);
        Countrie::create(['iso' => 'TG', 'pais' => 'Togo',]);
        Countrie::create(['iso' => 'TK', 'pais' => 'Tokelau',]);
        Countrie::create(['iso' => 'TO', 'pais' => 'Tonga',]);
        Countrie::create(['iso' => 'TT', 'pais' => 'Trinidad y Tobago',]);
        Countrie::create(['iso' => 'TN', 'pais' => 'Túnez',]);
        Countrie::create(['iso' => 'TC', 'pais' => 'Islas Turcas y Caicos',]);
        Countrie::create(['iso' => 'TM', 'pais' => 'Turkmenistán',]);
        Countrie::create(['iso' => 'TR', 'pais' => 'Turquía',]);
        Countrie::create(['iso' => 'TV', 'pais' => 'Tuvalu',]);
        Countrie::create(['iso' => 'UA', 'pais' => 'Ucrania',]);
        Countrie::create(['iso' => 'UG', 'pais' => 'Uganda',]);
        Countrie::create(['iso' => 'UY', 'pais' => 'Uruguay',]);
        Countrie::create(['iso' => 'UZ', 'pais' => 'Uzbekistán',]);
        Countrie::create(['iso' => 'VU', 'pais' => 'Vanuatu',]);
        Countrie::create(['iso' => 'VE', 'pais' => 'Venezuela',]);
        Countrie::create(['iso' => 'VN', 'pais' => 'Vietnam',]);
        Countrie::create(['iso' => 'VG', 'pais' => 'Islas Vírgenes Británicas',]);
        Countrie::create(['iso' => 'VI', 'pais' => 'Islas Vírgenes de los Estados Unidos',]);
        Countrie::create(['iso' => 'WF', 'pais' => 'Wallis y Futuna',]);
        Countrie::create(['iso' => 'YE', 'pais' => 'Yemen',]);
        Countrie::create(['iso' => 'DJ', 'pais' => 'Yibuti',]);
        Countrie::create(['iso' => 'ZM', 'pais' => 'Zambia',]);
        Countrie::create(['iso' => 'ZW', 'pais' => 'Zimbabue',]);
    }

}
